"
Used when we need to represent null note object behavior
"
Class {
	#name : 'NTNullNoteObject',
	#superclass : 'Object',
	#category : 'TheNoteTaker-Core',
	#package : 'TheNoteTaker',
	#tag : 'Core'
}

{ #category : 'accessing' }
NTNullNoteObject >> content: aString [
]

{ #category : 'accessing' }
NTNullNoteObject >> contents: aString [

	
]

{ #category : 'accessing' }
NTNullNoteObject >> title [

	^ ' '
]
